# Generated by Django 5.1.1 on 2024-10-02 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                ("task", models.CharField(max_length=200)),
                ("due_by", models.DateTimeField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "LOW"), (2, "MEDIUM"), (3, "HIGH")]
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignee", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["task"],
                "indexes": [
                    models.Index(fields=["id"], name="tasks_task_id_3f110b_idx"),
                    models.Index(fields=["task"], name="tasks_task_task_52d46d_idx"),
                    models.Index(
                        fields=["-created_at"], name="tasks_task_created_5da2cb_idx"
                    ),
                ],
            },
        ),
    ]
