# Generated by Django 5.1.1 on 2024-10-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_tasks_task_id_3f110b_idx_tasks_id_a24244_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user_email",
            field=models.EmailField(max_length=254),
        ),
    ]
