# Generated by Django 5.1.1 on 2024-10-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="author",
            new_name="created_by",
        ),
    ]
